# This is a basic workflow to help you get started with Actions

name: Package for deno

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone Github Repo Action
        # You may pin to the exact commit or the version.
        # uses: GuillaumeFalourd/clone-github-repo-action@d667f8c39e6ac1dd5309ad51b0020657c7a1a296
        uses: GuillaumeFalourd/clone-github-repo-action@v1
        with:
          # Repository Owner
          owner: connor4312
          # Repository name
          repository: cockatiel
        
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
        
      - name: Access cloned repository content
        run: |
          cd cockatiel
          sudo mv src/index.ts src/mod.ts
          sudo npm install
          sudo npm install denoify
          sudo npx denoify
          echo "ls -la----------------"
          pwd
          ls -la
          echo "ls -la deno_dist----------------"
          pwd
          ls deno_dist
          cd ..

          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: 'myrepo'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd myrepo
          sudo rm -rf **/*.ts
          ls ../cockatiel/deno_dist
          sudo cp -r ../cockatiel/deno_dist/* .
          echo "ls -la----------------"
          pwd
          ls -la
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: 'myrepo'
          
